const router = require('express').Router()
const AuthRouter = require('./AuthRouter')
const UserRouter = require('./UserRouter')
const PostRouter = require('./PostRouter')
const CommentRouter = require('./CommentRouter')
router.use('/auth', AuthRouter)
router.use('/user', UserRouter)
router.use('/post', PostRouter)
router.use('/comment', CommentRouter)
module.exports = router